# Generated by Django 6.0.8 on 2026-08-20 07:52

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='نام کسب\u200cوکار')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کسب\u200cوکار')),
                ('website', models.URLField(blank=True, verbose_name='وبسایت')),
                ('can_create_free_campaign', models.BooleanField(default=False, verbose_name='میتواند کمپین رایگان بسازد؟')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تبلیغ دهنده',
                'verbose_name_plural': 'تبلیغ دهندگان',
                'ordering': ['-created_at'],
            },
        ),
    ]
