# Generated by Django 6.0.2 on 2026-05-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='city',
        ),
    ]
