# Generated by Django 6.0.2 on 2026-04-20 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='province',
        ),
    ]
