# Generated by Django 6.0.2 on 2026-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_remove_advertiserprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='can_create_free_campaign',
            field=models.BooleanField(default=False, verbose_name='میتواند کمپین رایگان بسازد؟'),
        ),
    ]
