# Generated by Django 6.0.2 on 2026-05-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisers', '0002_remove_advertiserprofile_city'),
        ('influencers', '0002_remove_influencerchannel_influencers_city_id_59294b_idx_and_more'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
