# Generated by Django 6.0.2 on 2026-04-09 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
