# Generated by Django 6.0.2 on 2026-03-22 10:00

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تیم')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=90, scale=1, size=[500, 500], upload_to='content_team/logos/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تیم تولید محتوا',
                'verbose_name_plural': 'تیم\u200cهای تولید محتوا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام خدمت')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً: fa-video)', max_length=50, verbose_name='آیکون')),
                ('unit', models.CharField(choices=[('minute', 'دقیقه'), ('project', 'پروژه')], max_length=20, verbose_name='واحد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('ad_type', models.ManyToManyField(related_name='content_service_type', to='campaigns.adtype', verbose_name='نوع تبلیغ')),
            ],
            options={
                'verbose_name': 'نوع خدمت تولید محتوا',
                'verbose_name_plural': 'انواع خدمات تولید محتوا',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContentServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_unit', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت (تومان)')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='زمان تحویل تقریبی (روز)')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('notes', models.TextField(blank=True, help_text='توضیحات اضافی درباره این خدمت', verbose_name='یادداشت\u200cها')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='content_team.contentservicetype', verbose_name='نوع خدمت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نرخ خدمت تیم',
                'verbose_name_plural': 'نرخ\u200cهای خدمات تیم\u200cها',
                'ordering': ['team', 'service_type'],
                'unique_together': {('team', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='دقیقه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_orders', to='campaigns.campaign', verbose_name='کمپین')),
                ('service_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content_team.contentservicerate', verbose_name='تعرفه سرویس')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content_team.contentteam', verbose_name='تیم تولید محتوا')),
            ],
            options={
                'verbose_name': 'سفارش تولید محتوا',
                'verbose_name_plural': 'سفارش\u200cهای تولید محتوا',
            },
        ),
        migrations.CreateModel(
            name='ContentTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدیر تیم'), ('editor', 'ادیتور'), ('writer', 'نویسنده'), ('designer', 'طراح'), ('videographer', 'فیلمبردار'), ('other', 'سایر')], max_length=50, verbose_name='نقش')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=90, scale=1, size=[500, 500], upload_to='content_team/members/avatars/', verbose_name='تصویر پروفایل')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content_team.contentteam', verbose_name='تیم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو تیم تولید محتوا',
                'verbose_name_plural': 'اعضای تیم تولید محتوا',
                'ordering': ['team', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='از 1 تا 5', verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reviews', to='advertisers.advertiserprofile', verbose_name='تبلیغ\u200cدهنده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='content_team.contentorder', verbose_name='سفارش')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نظر درباره تیم',
                'verbose_name_plural': 'نظرات درباره تیم\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
