# Generated by Django 6.0.2 on 2026-07-26 06:29

import content_team.utils
import core.utils.utils
import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0002_initial'),
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تیم')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, default=core.utils.utils.generate_random_slug, unique=True, verbose_name='شناسه')),
                ('qr_code', models.ImageField(blank=True, help_text='QR Code برای اشتراک گذاری پروفایل تیم', null=True, upload_to='teams/qr_codes/', verbose_name='QR Code')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[500, 500], upload_to='content_team/logos/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تیم تولید محتوا',
                'verbose_name_plural': 'تیم\u200cهای تولید محتوا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(help_text='قیمت نهایی از روی پلن کپی می\u200cشود', verbose_name='قیمت')),
                ('selected_quantity', models.PositiveIntegerField(blank=True, help_text='مقداری که کاربر انتخاب کرده (در صورت قابل تنظیم بودن)', null=True, verbose_name='مقدار انتخابی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('review_pending', 'در انتظار ویرایش'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('deadline', django_jalali.db.models.jDateTimeField(blank=True, help_text='تاریخ و زمان نهایی تحویل سفارش', null=True, verbose_name='ددلاین تحویل')),
                ('deadline_timestamp', models.BigIntegerField(blank=True, help_text='تایم\u200cاستمپ ددلاین به میلی\u200cثانیه', null=True, verbose_name='ددلاین تحویل (Unix Timestamp)')),
                ('replaced_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ جایگزینی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_orders', to='campaigns.campaign', verbose_name='کمپین')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_orders', to='content_team.contentorder', verbose_name='جایگزین شده توسط')),
            ],
            options={
                'verbose_name': 'سفارش تولید محتوا',
                'verbose_name_plural': 'سفارش\u200cهای تولید محتوا',
            },
        ),
        migrations.CreateModel(
            name='ContentOrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('product_intro', 'معرفی محصول یا خدمت'), ('brand_awareness', 'افزایش آگاهی از برند'), ('sale_campaign', 'کمپین فروش یا تخفیف'), ('educational', 'محتوای آموزشی'), ('engagement', 'افزایش تعامل مخاطب'), ('other', 'سایر')], max_length=50, verbose_name='هدف محتوا')),
                ('goal_description', models.CharField(blank=True, help_text='اگر "سایر" انتخاب کردید توضیح دهید', max_length=200, null=True, verbose_name='توضیح هدف')),
                ('tone', models.CharField(choices=[('formal', 'رسمی'), ('friendly', 'صمیمی'), ('humorous', 'طنز'), ('emotional', 'احساسی'), ('motivational', 'انگیزشی')], max_length=30, verbose_name='لحن محتوا')),
                ('brand_name', models.CharField(max_length=100, verbose_name='نام برند یا محصول')),
                ('hashtags', models.CharField(blank=True, help_text='مثلاً: #برند_من #تخفیف', max_length=500, verbose_name='هشتگ\u200cها')),
                ('reference_links', models.TextField(blank=True, help_text='لینک نمونه\u200cکارهای مشابه که دوست دارید', verbose_name='لینک\u200cهای مرجع')),
                ('target_audience', models.CharField(blank=True, help_text='مثلاً: زنان ۲۵-۳۵ ساله علاقه\u200cمند به مد', max_length=300, verbose_name='مخاطب هدف')),
                ('description', models.TextField(help_text='هر اطلاعات دیگری که تیم باید بداند', verbose_name='توضیحات کامل')),
                ('do_not_include', models.TextField(blank=True, help_text='مثلاً: رنگ قرمز، افکت\u200cهای بصری خاص، لوگوی رقبا', verbose_name='چه چیزهایی نباشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='content_team.contentorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'توضیح سفارش',
                'verbose_name_plural': 'توضیحات سفارش',
            },
        ),
        migrations.CreateModel(
            name='ContentOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=content_team.utils.content_order_file_path, verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صدا'), ('document', 'سند'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('description', models.CharField(blank=True, help_text='این فایل چیست؟ مثلاً: لوگوی برند', max_length=200, verbose_name='توضیح فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('uploaded_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content_team.contentorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فایل سفارش',
                'verbose_name_plural': 'فایل\u200cهای سفارش',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentOrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='مشخص کنید چه تغییراتی می\u200cخواهید', verbose_name='توضیحات ویرایش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('done', 'انجام شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('file', models.FileField(blank=True, help_text='فایل مرجع برای ویرایش (اختیاری)', null=True, upload_to='revision_files/', verbose_name='فایل مرجع')),
                ('file_name', models.CharField(blank=True, help_text='نام اصلی فایل آپلود شده', max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content_team.contentorder', verbose_name='سفارش')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_revisions', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست ویرایش',
                'verbose_name_plural': 'درخواست\u200cهای ویرایش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: "موشن ساده" یا "پکیج ۳ پوستر"', max_length=200, verbose_name='نام پلن')),
                ('description', models.TextField(blank=True, help_text='توضیح کامل این پلن شامل چه چیزایی میشه', verbose_name='توضیحات پلن')),
                ('features', models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cهای این پلن. مثال: ["۲ دوربین 4K", "تدوین حرفه\u200cای"]', verbose_name='ویژگی\u200cها')),
                ('pricing_unit', models.CharField(choices=[('second', 'ثانیه'), ('minute', 'دقیقه'), ('quantity', 'تعدادی')], help_text='واحد اندازه\u200cگیری برای این پلن (ثانیه، دقیقه، یا تعدادی)', max_length=20, verbose_name='واحد قیمت\u200cگذاری')),
                ('base_quantity', models.PositiveIntegerField(blank=True, help_text='مقدار پایه این پلن. مثلاً ۲۰ برای ۲۰ ثانیه، یا ۳ دقیقه. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='مقدار پایه')),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='حداقل مقداری که این پلن پوشش میدهد. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='حداقل مقدار')),
                ('max_quantity', models.PositiveIntegerField(blank=True, help_text='حداکثر مقداری که این پلن پوشش میدهد. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='حداکثر مقدار')),
                ('price', models.PositiveBigIntegerField(help_text='قیمت کاملاً مشخص این پلن. مثلاً ۲۵۰,۰۰۰ تومان', verbose_name='قیمت نهایی (تومان)')),
                ('delivery_type', models.CharField(choices=[('single', 'تحویل یک فایل'), ('multi_choice', 'تحویل چند گزینه و انتخاب یکی')], default='single', help_text='نحوه تحویل فایل\u200cها به کاربر', max_length=20, verbose_name='نوع تحویل')),
                ('delivery_options_count', models.PositiveIntegerField(blank=True, help_text='برای نوع تحویل MULTI_CHOICE: چند گزینه به کاربر داده میشه؟', null=True, verbose_name='تعداد گزینه\u200cهای تحویلی')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=5, help_text='حداکثر چند روز کاری طول میکشه تا تحویل داده بشه', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت آماده سازی')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این پلن در حال حاضر قابل سفارش هست؟', verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='core.contentservicetype', verbose_name='نوع خدمت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'پلن خدمت',
                'verbose_name_plural': 'پلن\u200cهای خدمات',
                'ordering': ['team', 'service_type', 'price'],
            },
        ),
        migrations.AddField(
            model_name='contentorder',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content_team.contentserviceplan', verbose_name='پلن انتخابی'),
        ),
        migrations.CreateModel(
            name='ContentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: ویدیوی معرفی محصول ایکس', max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, help_text='توضیح درباره این نمونه کار', verbose_name='توضیحات')),
                ('media', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[800, 800], upload_to='team_portfolio/', verbose_name='تصویر نمونه کار')),
                ('video_url', models.URLField(blank=True, help_text='لینک آپارات، یوتیوب، ویمئو و...', verbose_name='لینک ویدیو')),
                ('external_link', models.URLField(blank=True, help_text='لینک به نمونه کار در سایت دیگر', verbose_name='لینک خارجی')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='core.contentservicetype', verbose_name='نوع خدمت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentorder',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content_team.contentteam', verbose_name='تیم تولید محتوا'),
        ),
        migrations.CreateModel(
            name='ContentTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'مدیر تیم'), ('editor', 'ادیتور'), ('writer', 'نویسنده'), ('designer', 'طراح'), ('videographer', 'فیلمبردار'), ('other', 'سایر')], max_length=50, verbose_name='نقش')),
                ('revenue_share_percent', models.PositiveSmallIntegerField(default=0, help_text='درصدی که این عضو از هر سفارش دریافت می\u200cکند (۰ تا ۱۰۰)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد سهم از درآمد')),
                ('bio', models.TextField(blank=True, verbose_name='بیوگرافی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content_team.contentteam', verbose_name='تیم')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'عضو تیم تولید محتوا',
                'verbose_name_plural': 'اعضای تیم تولید محتوا',
                'ordering': ['team', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحویل'), ('delivered', 'تحویل داده شد'), ('revision_requested', 'درخواست ویرایش'), ('final_accepted', 'تأیید نهایی')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت تحویل')),
                ('delivered_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('notes', models.TextField(blank=True, help_text='توضیحات تکمیلی برای سفارش\u200cدهنده', verbose_name='توضیحات تحویل')),
                ('accepted_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید نهایی')),
                ('version', models.PositiveSmallIntegerField(default=1, help_text='نسخه تحویل سفارش (۱ برای تحویل اولیه، ۲ برای ویرایش اول، و...)', verbose_name='نسخه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='content_team.contentorder', verbose_name='سفارش')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='content_team.contentteammember', verbose_name='تحویل\u200cدهنده')),
            ],
            options={
                'verbose_name': 'تحویل سفارش',
                'verbose_name_plural': 'تحویل\u200cهای سفارش',
                'ordering': ['-version', '-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='content_team.contentteam', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_join_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست عضویت در تیم',
                'verbose_name_plural': 'درخواست\u200cهای عضویت در تیم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='از 1 تا 5', verbose_name='امتیاز')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reviews', to='advertisers.advertiserprofile', verbose_name='تبلیغ\u200cدهنده')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='content_team.contentorder', verbose_name='سفارش')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نظر درباره تیم',
                'verbose_name_plural': 'نظرات درباره تیم\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentDeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل تحویل داده شده توسط تیم', upload_to=content_team.utils.content_order_file_path, verbose_name='فایل')),
                ('file_name', models.CharField(blank=True, help_text='نام اصلی فایل آپلود شده', max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('is_option', models.BooleanField(default=False, help_text='آیا این فایل یکی از گزینه\u200cهای تحویلی است؟ (برای MULTI_CHOICE)', verbose_name='گزینه')),
                ('option_number', models.PositiveSmallIntegerField(blank=True, help_text='شماره گزینه (۱، ۲، ۳، ...)', null=True, verbose_name='شماره گزینه')),
                ('is_selected', models.BooleanField(default=False, help_text='آیا این فایل توسط تبلیغ\u200cدهنده به عنوان فایل نهایی انتخاب شده است؟', verbose_name='انتخاب شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content_team.contentdelivery', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'فایل تحویل',
                'verbose_name_plural': 'فایل\u200cهای تحویل',
                'ordering': ['option_number', 'created_at'],
                'indexes': [models.Index(fields=['delivery', 'is_option'], name='content_tea_deliver_b9a92e_idx'), models.Index(fields=['option_number'], name='content_tea_option__32a7a5_idx'), models.Index(fields=['is_selected'], name='content_tea_is_sele_b3e875_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contentserviceplan',
            index=models.Index(fields=['team', 'service_type', 'is_active'], name='content_tea_team_id_20009b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserviceplan',
            index=models.Index(fields=['price'], name='content_tea_price_b0a609_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentserviceplan',
            unique_together={('team', 'service_type', 'name')},
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['order', 'version'], name='content_tea_order_i_6ef2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['status'], name='content_tea_status_19b655_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together={('team', 'user')},
        ),
    ]
