# Generated by Django 6.0.2 on 2026-03-25 10:33

import content_team.models
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentorder',
            name='description',
        ),
        migrations.CreateModel(
            name='ContentOrderDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(choices=[('product_intro', 'معرفی محصول یا خدمت'), ('brand_awareness', 'افزایش آگاهی از برند'), ('sale_campaign', 'کمپین فروش یا تخفیف'), ('educational', 'محتوای آموزشی'), ('engagement', 'افزایش تعامل مخاطب'), ('other', 'سایر')], default='product_intro', max_length=50, verbose_name='هدف محتوا')),
                ('goal_description', models.CharField(blank=True, help_text='اگر "سایر" انتخاب کردید توضیح دهید', max_length=200, verbose_name='توضیح هدف')),
                ('tone', models.CharField(choices=[('formal', 'رسمی'), ('friendly', 'صمیمی'), ('humorous', 'طنز'), ('emotional', 'احساسی'), ('motivational', 'انگیزشی')], default='friendly', max_length=30, verbose_name='لحن محتوا')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='نام برند یا محصول')),
                ('hashtags', models.CharField(blank=True, help_text='مثلاً: #برند_من #تخفیف', max_length=500, verbose_name='هشتگ\u200cها')),
                ('reference_links', models.TextField(blank=True, help_text='لینک نمونه\u200cکارهای مشابه که دوست دارید', verbose_name='لینک\u200cهای مرجع')),
                ('target_audience', models.CharField(blank=True, help_text='مثلاً: زنان ۲۵-۳۵ ساله علاقه\u200cمند به مد', max_length=300, verbose_name='مخاطب هدف')),
                ('description', models.TextField(help_text='هر اطلاعات دیگری که تیم باید بداند', verbose_name='توضیحات کامل')),
                ('do_not_include', models.TextField(blank=True, help_text='مثلاً: رنگ قرمز، افکت\u200cهای بصری خاص، لوگوی رقبا', verbose_name='چه چیزهایی نباشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='content_team.contentorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'توضیح سفارش',
                'verbose_name_plural': 'توضیحات سفارش',
            },
        ),
        migrations.CreateModel(
            name='ContentOrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=content_team.models.content_order_file_path, verbose_name='فایل')),
                ('file_type', models.CharField(choices=[('image', 'تصویر'), ('video', 'ویدیو'), ('audio', 'صدا'), ('document', 'سند'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('description', models.CharField(blank=True, help_text='این فایل چیست؟ مثلاً: لوگوی برند', max_length=200, verbose_name='توضیح فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('uploaded_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content_team.contentorder', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'فایل سفارش',
                'verbose_name_plural': 'فایل\u200cهای سفارش',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
