# Generated by Django 6.0.2 on 2026-06-02 20:17

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentportfolio',
            name='media',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[800, 800], upload_to='team_portfolio/', verbose_name='تصویر نمونه کار'),
        ),
        migrations.AlterField(
            model_name='contentteam',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[500, 500], upload_to='content_team/logos/', verbose_name='لوگو'),
        ),
    ]
