# Generated by Django 6.0.8 on 2026-09-07 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('content_team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='is_standalone',
            field=models.BooleanField(default=False, verbose_name='سفارش مستقل (بدون کمپین)'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='standalone_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_content_orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر سفارش\u200cدهنده (بدون کمپین)'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_orders', to='campaigns.campaign', verbose_name='کمپین'),
        ),
    ]
