# Generated by Django 6.0.2 on 2026-05-12 22:14

import django.core.validators
import django.db.models.deletion
import django_jalali.db.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentorder',
            name='service_rate',
        ),
        migrations.CreateModel(
            name='ContentServicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثلاً: "پلن اقتصادی - دو دوربین" یا "پکیج حرفه\u200cای - چهار دوربین"', max_length=200, verbose_name='نام پلن')),
                ('description', models.TextField(help_text='توضیح کامل این پلن شامل چه چیزایی میشه', verbose_name='توضیحات پلن')),
                ('features', models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cهای این پلن. مثال: ["۲ دوربین 4K", "تدوین حرفه\u200cای", "موزیک متن", "تحویل ۳ روزه"]', verbose_name='ویژگی\u200cها')),
                ('price_per_unit', models.DecimalField(decimal_places=0, help_text='قیمت برای هر دقیقه/پروژه', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='قیمت به ازای واحد (تومان)')),
                ('estimated_delivery_days', models.PositiveIntegerField(default=5, help_text='حداکثر چند روز کاری طول میکشه تا تحویل داده بشه', validators=[django.core.validators.MinValueValidator(1)], verbose_name='زمان تحویل تقریبی (روز کاری)')),
                ('is_active', models.BooleanField(default=True, help_text='آیا این پلن در حال حاضر قابل سفارش هست؟', verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='content_team.contentservicetype', verbose_name='نوع خدمت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_plans', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'پلن خدمت',
                'verbose_name_plural': 'پلن\u200cهای خدمات',
                'ordering': ['team', 'service_type', 'price_per_unit'],
            },
        ),
        migrations.AddField(
            model_name='contentorder',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='content_team.contentserviceplan', verbose_name='پلن انتخابی'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ContentServiceRate',
        ),
        migrations.AddIndex(
            model_name='contentserviceplan',
            index=models.Index(fields=['team', 'service_type', 'is_active'], name='content_tea_team_id_20009b_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserviceplan',
            index=models.Index(fields=['price_per_unit'], name='content_tea_price_p_b84046_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentserviceplan',
            unique_together={('team', 'service_type', 'name')},
        ),
    ]
