# Generated by Django 6.0.2 on 2026-07-02 07:36

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='replaced_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ جایگزینی'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_orders', to='content_team.contentorder', verbose_name='جایگزین شده توسط'),
        ),
    ]
