# Generated by Django 6.0.8 on 2026-08-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentdelivery',
            options={'ordering': ['-version', '-delivered_at'], 'verbose_name': 'تحویل سفارش', 'verbose_name_plural': 'تحویل های سفارش'},
        ),
        migrations.AlterModelOptions(
            name='contentdeliveryfile',
            options={'ordering': ['option_number', 'created_at'], 'verbose_name': 'فایل تحویل', 'verbose_name_plural': 'فایل های تحویل'},
        ),
        migrations.AlterModelOptions(
            name='contentorder',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='contentorderfile',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'فایل سفارش', 'verbose_name_plural': 'فایل های سفارش'},
        ),
        migrations.AlterModelOptions(
            name='contentorderrevision',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست ویرایش', 'verbose_name_plural': 'درخواست های ویرایش'},
        ),
        migrations.AlterModelOptions(
            name='contentserviceplan',
            options={'ordering': ['team', 'service_type', 'price'], 'verbose_name': 'پلن', 'verbose_name_plural': 'پلن ها'},
        ),
        migrations.AlterModelOptions(
            name='contentteam',
            options={'ordering': ['name'], 'verbose_name': 'تیم تولید محتوا', 'verbose_name_plural': 'تیم های تولید محتوا'},
        ),
        migrations.AlterModelOptions(
            name='contentteammember',
            options={'ordering': ['team', 'created_at'], 'verbose_name': 'عضو تیم', 'verbose_name_plural': 'اعضای تیم'},
        ),
        migrations.AlterModelOptions(
            name='teamjoinrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست عضویت', 'verbose_name_plural': 'درخواست های عضویت'},
        ),
        migrations.AlterModelOptions(
            name='teamreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'بازخورد تیم', 'verbose_name_plural': 'بازخورد های تیم'},
        ),
    ]
