# Generated by Django 6.0.2 on 2026-05-24 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0002_remove_contentorder_service_rate_contentserviceplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentserviceplan',
            name='estimated_delivery_days',
            field=models.PositiveIntegerField(default=5, help_text='حداکثر چند روز کاری طول میکشه تا تحویل داده بشه', validators=[django.core.validators.MinValueValidator(1)], verbose_name='مدت آماده سازی'),
        ),
    ]
