# Generated by Django 6.0.2 on 2026-07-10 12:01

import content_team.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0002_contentorder_replaced_at_contentorder_replaced_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentserviceplan',
            options={'ordering': ['team', 'service_type', 'price'], 'verbose_name': 'پلن خدمت', 'verbose_name_plural': 'پلن\u200cهای خدمات'},
        ),
        migrations.RemoveIndex(
            model_name='contentserviceplan',
            name='content_tea_price_p_b84046_idx',
        ),
        migrations.AlterUniqueTogether(
            name='contentdelivery',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contentorder',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='contentservicetype',
            name='unit',
        ),
        migrations.AddField(
            model_name='contentdelivery',
            name='is_option',
            field=models.BooleanField(default=False, help_text='آیا این فایل یکی از گزینه\u200cهای تحویلی است؟ (برای MULTI_CHOICE)', verbose_name='گزینه انتخابی'),
        ),
        migrations.AddField(
            model_name='contentdelivery',
            name='option_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='شماره گزینه (۱، ۲، ۳، ...)', null=True, verbose_name='شماره گزینه'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='selected_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='مقداری که کاربر انتخاب کرده (در صورت قابل تنظیم بودن)', null=True, verbose_name='مقدار انتخابی'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='base_quantity',
            field=models.PositiveIntegerField(default=1, help_text='مقدار پایه این پلن. مثلاً ۲۰ برای ۲۰ ثانیه، یا ۳ برای ۳ عدد پوستر', verbose_name='مقدار پایه'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='delivery_options_count',
            field=models.PositiveIntegerField(blank=True, help_text='برای نوع تحویل MULTI_CHOICE: چند گزینه به کاربر داده میشه؟', null=True, verbose_name='تعداد گزینه\u200cهای تحویلی'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='delivery_type',
            field=models.CharField(choices=[('single', 'تحویل یک فایل'), ('multi_choice', 'تحویل چند گزینه و انتخاب یکی'), ('multi_all', 'تحویل همه فایل\u200cها')], default='single', help_text='نحوه تحویل فایل\u200cها به کاربر', max_length=20, verbose_name='نوع تحویل'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر مقداری که این پلن پوشش میدهد (اختیاری)', null=True, verbose_name='حداکثر مقدار'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='min_quantity',
            field=models.PositiveIntegerField(default=1, help_text='حداقل مقداری که این پلن پوشش میدهد', verbose_name='حداقل مقدار'),
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='price',
            field=models.PositiveBigIntegerField(default=0, help_text='قیمت کاملاً مشخص این پلن. مثلاً ۲۵۰,۰۰۰ تومان', verbose_name='قیمت نهایی (تومان)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentserviceplan',
            name='pricing_unit',
            field=models.CharField(choices=[('second', 'ثانیه'), ('minute', 'دقیقه'), ('quantity', 'تعدادی')], default='minute', help_text='واحد اندازه\u200cگیری برای این پلن (ثانیه، دقیقه، یا تعدادی)', max_length=20, verbose_name='واحد قیمت\u200cگذاری'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentservicetype',
            name='allowed_units',
            field=models.JSONField(blank=True, default=list, help_text='واحدهایی که این سرویس می\u200cتواند داشته باشد. مثال: ["second", "minute", "quantity"]', verbose_name='واحدهای مجاز'),
        ),
        migrations.AlterField(
            model_name='contentdelivery',
            name='file',
            field=models.FileField(blank=True, help_text='فایل تحویل شده توسط تیم', null=True, upload_to=content_team.utils.content_order_file_path, verbose_name='فایل تحویلی'),
        ),
        migrations.AlterField(
            model_name='contentdelivery',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='content_team.contentorder', verbose_name='سفارش'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='deadline_timestamp',
            field=models.BigIntegerField(blank=True, help_text='تایم\u200cاستمپ ددلاین به میلی\u200cثانیه', null=True, verbose_name='ددلاین تحویل (Unix Timestamp)'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='price',
            field=models.PositiveBigIntegerField(help_text='قیمت نهایی از روی پلن کپی می\u200cشود', verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('review_pending', 'در انتظار ویرایش'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='لیست ویژگی\u200cهای این پلن. مثال: ["۲ دوربین 4K", "تدوین حرفه\u200cای"]', verbose_name='ویژگی\u200cها'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='name',
            field=models.CharField(help_text='مثلاً: "موشن ساده" یا "پکیج ۳ پوستر"', max_length=200, verbose_name='نام پلن'),
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['order', 'version'], name='content_tea_order_i_6ef2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='contentdelivery',
            index=models.Index(fields=['status'], name='content_tea_status_19b655_idx'),
        ),
        migrations.AddIndex(
            model_name='contentserviceplan',
            index=models.Index(fields=['price'], name='content_tea_price_b0a609_idx'),
        ),
        migrations.RemoveField(
            model_name='contentserviceplan',
            name='price_per_unit',
        ),
    ]
