# Generated by Django 6.0.2 on 2026-06-02 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0002_alter_contentportfolio_media_alter_contentteam_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamreview',
            name='comment',
            field=models.TextField(verbose_name='نظر'),
        ),
        migrations.AlterField(
            model_name='teamreview',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='content_team.contentorder', verbose_name='سفارش'),
        ),
    ]
