# Generated by Django 6.0.8 on 2026-09-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0002_contentorder_is_standalone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentorder',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار'), ('review_pending', 'در انتظار ویرایش'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
