# Generated by Django 6.0.2 on 2026-07-12 12:22

import content_team.utils
import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0003_alter_contentserviceplan_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentdelivery',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contentdelivery',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='contentdelivery',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='contentdelivery',
            name='is_option',
        ),
        migrations.RemoveField(
            model_name='contentdelivery',
            name='option_number',
        ),
        migrations.CreateModel(
            name='ContentDeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='فایل تحویل داده شده توسط تیم', upload_to=content_team.utils.content_order_file_path, verbose_name='فایل')),
                ('file_name', models.CharField(blank=True, help_text='نام اصلی فایل آپلود شده', max_length=255, verbose_name='نام فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('is_option', models.BooleanField(default=False, help_text='آیا این فایل یکی از گزینه\u200cهای تحویلی است؟ (برای MULTI_CHOICE)', verbose_name='گزینه انتخابی')),
                ('option_number', models.PositiveSmallIntegerField(blank=True, help_text='شماره گزینه (۱، ۲، ۳، ...)', null=True, verbose_name='شماره گزینه')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content_team.contentdelivery', verbose_name='تحویل')),
            ],
            options={
                'verbose_name': 'فایل تحویل',
                'verbose_name_plural': 'فایل\u200cهای تحویل',
                'ordering': ['option_number', 'created_at'],
                'indexes': [models.Index(fields=['delivery', 'is_option'], name='content_tea_deliver_b9a92e_idx'), models.Index(fields=['option_number'], name='content_tea_option__32a7a5_idx')],
            },
        ),
    ]
