# Generated by Django 6.0.2 on 2026-06-06 19:54

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0003_alter_teamreview_comment_alter_teamreview_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='deadline',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='تاریخ و زمان نهایی تحویل سفارش', null=True, verbose_name='ددلاین تحویل'),
        ),
    ]
