# Generated by Django 6.0.8 on 2026-09-09 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0003_alter_contentorder_status'),
        ('payment', '0007_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='content_team_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_content_team_orders', to='payment.coupon', verbose_name='کد تخفیف تیم محتوا'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='platform_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standalone_platform_orders', to='payment.coupon', verbose_name='کد تخفیف پلتفرم'),
        ),
    ]
