# Generated by Django 6.0.2 on 2026-03-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0003_alter_contentorderdescription_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentorderdescription',
            name='brand_name',
            field=models.CharField(max_length=100, verbose_name='نام برند یا محصول'),
        ),
        migrations.AlterField(
            model_name='contentorderdescription',
            name='goal',
            field=models.CharField(choices=[('product_intro', 'معرفی محصول یا خدمت'), ('brand_awareness', 'افزایش آگاهی از برند'), ('sale_campaign', 'کمپین فروش یا تخفیف'), ('educational', 'محتوای آموزشی'), ('engagement', 'افزایش تعامل مخاطب'), ('other', 'سایر')], max_length=50, verbose_name='هدف محتوا'),
        ),
        migrations.AlterField(
            model_name='contentorderdescription',
            name='goal_description',
            field=models.CharField(blank=True, help_text='اگر "سایر" انتخاب کردید توضیح دهید', max_length=200, null=True, verbose_name='توضیح هدف'),
        ),
        migrations.AlterField(
            model_name='contentorderdescription',
            name='tone',
            field=models.CharField(choices=[('formal', 'رسمی'), ('friendly', 'صمیمی'), ('humorous', 'طنز'), ('emotional', 'احساسی'), ('motivational', 'انگیزشی')], default=None, max_length=30, verbose_name='لحن محتوا'),
            preserve_default=False,
        ),
    ]
