# Generated by Django 6.0.2 on 2026-06-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0004_contentorder_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='deadline_timestamp',
            field=models.BigIntegerField(blank=True, help_text='تایم\u200cاستمپ ددلاین به میلی \u200cثانیه', null=True, verbose_name='ددلاین تحویل (Unix Timestamp)'),
        ),
    ]
