# Generated by Django 6.0.2 on 2026-07-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0004_remove_contentdelivery_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdeliveryfile',
            name='is_selected',
            field=models.BooleanField(default=False, help_text='آیا این فایل توسط تبلیغ\u200cدهنده به عنوان فایل نهایی انتخاب شده است؟', verbose_name='انتخاب شده'),
        ),
        migrations.AlterField(
            model_name='contentdeliveryfile',
            name='is_option',
            field=models.BooleanField(default=False, help_text='آیا این فایل یکی از گزینه\u200cهای تحویلی است؟ (برای MULTI_CHOICE)', verbose_name='گزینه'),
        ),
        migrations.AddIndex(
            model_name='contentdeliveryfile',
            index=models.Index(fields=['is_selected'], name='content_tea_is_sele_b3e875_idx'),
        ),
    ]
