# Generated by Django 6.0.2 on 2026-04-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0004_alter_contentorderdescription_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentteammember',
            name='avatar',
        ),
        migrations.AddField(
            model_name='contentteammember',
            name='revenue_share_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصدی که این عضو از هر سفارش دریافت می\u200cکند (۰ تا ۱۰۰)', verbose_name='درصد سهم از درآمد'),
        ),
    ]
