# Generated by Django 6.0.8 on 2026-09-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0004_contentorder_content_team_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='name',
            field=models.CharField(blank=True, help_text='برای سفارش\u200cهای کمپینی خودکار از نام کمپین پر می\u200cشود', max_length=255, verbose_name='نام سفارش'),
        ),
    ]
