# Generated by Django 6.0.2 on 2026-04-07 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0005_remove_contentteammember_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentteammember',
            name='revenue_share_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='درصدی که این عضو از هر سفارش دریافت می\u200cکند (۰ تا ۱۰۰)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد سهم از درآمد'),
        ),
    ]
