# Generated by Django 6.0.2 on 2026-07-14 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0005_contentdeliveryfile_is_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تحویل'), ('delivered', 'تحویل داده شد'), ('revision_requested', 'درخواست ویرایش'), ('final_accepted', 'تأیید نهایی')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت تحویل'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('review_pending', 'در انتظار ویرایش'), ('in_progress', 'در حال انجام'), ('done', 'انجام شده'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='base_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='مقدار پایه این پلن. مثلاً ۲۰ برای ۲۰ ثانیه، یا ۳ دقیقه. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='مقدار پایه'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='delivery_type',
            field=models.CharField(choices=[('single', 'تحویل یک فایل'), ('multi_choice', 'تحویل چند گزینه و انتخاب یکی')], default='single', help_text='نحوه تحویل فایل\u200cها به کاربر', max_length=20, verbose_name='نوع تحویل'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح کامل این پلن شامل چه چیزایی میشه', verbose_name='توضیحات پلن'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='max_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='حداکثر مقداری که این پلن پوشش میدهد. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='حداکثر مقدار'),
        ),
        migrations.AlterField(
            model_name='contentserviceplan',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='حداقل مقداری که این پلن پوشش میدهد. (فقط برای واحدهای ثانیه و دقیقه)', null=True, verbose_name='حداقل مقدار'),
        ),
    ]
