# Generated by Django 6.0.8 on 2026-09-12 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0005_contentorder_name'),
        ('core', '0002_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentteam',
            name='province',
            field=models.ForeignKey(blank=True, help_text='استانی که این تیم در آن فعالیت می\u200cکند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_teams', to='core.province', verbose_name='استان'),
        ),
    ]
