# Generated by Django 6.0.8 on 2026-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0006_contentteam_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentorder',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, help_text='مقداری که از قیمت اولیه کم شده', verbose_name='مقدار تخفیف'),
        ),
        migrations.AddField(
            model_name='contentorder',
            name='original_price',
            field=models.PositiveBigIntegerField(blank=True, help_text='قیمت اصلی قبل از اعمال کد تخفیف', null=True, verbose_name='قیمت اولیه (قبل از تخفیف)'),
        ),
    ]
