# Generated by Django 6.0.2 on 2026-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0006_alter_contentdelivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentteam',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code برای اشتراک گذاری پروفایل تیم', null=True, upload_to='teams/qr_codes/', verbose_name='QR Code'),
        ),
    ]
