# Generated by Django 6.0.2 on 2026-04-07 08:25

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0006_alter_contentteammember_revenue_share_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentteam',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, default=core.utils.generate_random_slug, unique=True, verbose_name='شناسه'),
        ),
    ]
