# Generated by Django 6.0.8 on 2026-09-16 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0007_contentorder_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentportfolio',
            options={'ordering': ['-created_at'], 'verbose_name': 'نمونه کار', 'verbose_name_plural': 'نمونه کارها'},
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='description',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='external_link',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='media',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='team',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='title',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='contentportfolio',
            name='video_url',
        ),
        migrations.AddField(
            model_name='contentportfolio',
            name='file',
            field=models.FileField(default=None, help_text='اشاره به فایل تحویل داده شده توسط تیم — بدون کپی فیزیکی', max_length=500, upload_to='', verbose_name='فایل نمونه کار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentportfolio',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='content_team.contentserviceplan', verbose_name='پلن'),
            preserve_default=False,
        ),
    ]
