# Generated by Django 6.0.2 on 2026-04-11 08:01

import content_team.models
import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0008_teamjoinrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDeliveryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=content_team.models.content_order_file_path, verbose_name='فایل')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='نام اصلی فایل')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='نوع فایل')),
                ('uploaded_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ آپلود')),
            ],
            options={
                'verbose_name': 'فایل تحویلی',
                'verbose_name_plural': 'فایل\u200cهای تحویلی',
            },
        ),
        migrations.CreateModel(
            name='ContentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تحویل'), ('delivered', 'تحویل داده شد'), ('partial', 'تحویل بخشی'), ('revision_requested', 'ویرایش درخواست شده'), ('final_accepted', 'تأیید نهایی')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت تحویل')),
                ('delivered_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل')),
                ('notes', models.TextField(blank=True, help_text='توضیحات تکمیلی برای سفارش\u200cدهنده', verbose_name='توضیحات تحویل')),
                ('accepted_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید نهایی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='content_team.contentteammember', verbose_name='تحویل\u200cدهنده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='content_team.contentorder', verbose_name='سفارش')),
                ('files', models.ManyToManyField(blank=True, to='content_team.contentdeliveryfile', verbose_name='فایل\u200cهای تحویلی')),
            ],
            options={
                'verbose_name': 'تحویل سفارش',
                'verbose_name_plural': 'تحویل\u200cهای سفارش',
                'ordering': ['-delivered_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentOrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(help_text='مشخص کنید چه تغییراتی می\u200cخواهید', verbose_name='توضیحات ویرایش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده'), ('done', 'انجام شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('files', models.ManyToManyField(blank=True, help_text='فایل\u200cهای مرجع برای ویرایش', to='content_team.contentdeliveryfile', verbose_name='فایل\u200cهای پیوست')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content_team.contentorder', verbose_name='سفارش')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_revisions', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cکننده')),
            ],
            options={
                'verbose_name': 'درخواست ویرایش',
                'verbose_name_plural': 'درخواست\u200cهای ویرایش',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلاً: ویدیوی معرفی محصول ایکس', max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, help_text='توضیح درباره این نمونه کار', verbose_name='توضیحات')),
                ('media', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=90, scale=1, size=[800, 800], upload_to='team_portfolio/', verbose_name='تصویر نمونه کار')),
                ('video_url', models.URLField(blank=True, help_text='لینک آپارات، یوتیوب، ویمئو و...', verbose_name='لینک ویدیو')),
                ('external_link', models.URLField(blank=True, help_text='لینک به نمونه کار در سایت دیگر', verbose_name='لینک خارجی')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('service_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='content_team.contentservicetype', verbose_name='نوع خدمت')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='content_team.contentteam', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
