# Generated by Django 6.0.2 on 2026-04-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0009_contentdeliveryfile_contentdelivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentdelivery',
            name='version',
            field=models.PositiveSmallIntegerField(default=1, help_text='نسخه تحویل سفارش (۱ برای تحویل اولیه، ۲ برای ویرایش اول، و...)', verbose_name='نسخه'),
        ),
    ]
