# Generated by Django 6.0.2 on 2026-04-12 08:25

import content_team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0010_contentdelivery_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentorderrevision',
            name='files',
        ),
        migrations.AlterModelOptions(
            name='contentdelivery',
            options={'ordering': ['-version', '-delivered_at'], 'verbose_name': 'تحویل سفارش', 'verbose_name_plural': 'تحویل\u200cهای سفارش'},
        ),
        migrations.AlterUniqueTogether(
            name='contentdelivery',
            unique_together={('order', 'version')},
        ),
        migrations.AddField(
            model_name='contentdelivery',
            name='file',
            field=models.FileField(blank=True, help_text='فایل نهایی تحویل شده توسط تیم', null=True, upload_to=content_team.models.content_order_file_path, verbose_name='فایل تحویلی'),
        ),
        migrations.AddField(
            model_name='contentdelivery',
            name='file_name',
            field=models.CharField(blank=True, help_text='نام اصلی فایل آپلود شده', max_length=255, verbose_name='نام فایل'),
        ),
        migrations.AddField(
            model_name='contentdelivery',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AddField(
            model_name='contentorderrevision',
            name='file',
            field=models.FileField(blank=True, help_text='فایل مرجع برای ویرایش (اختیاری)', null=True, upload_to='revision_files/', verbose_name='فایل مرجع'),
        ),
        migrations.AddField(
            model_name='contentorderrevision',
            name='file_name',
            field=models.CharField(blank=True, help_text='نام اصلی فایل آپلود شده', max_length=255, verbose_name='نام فایل'),
        ),
        migrations.AddField(
            model_name='contentorderrevision',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حجم فایل (بایت)'),
        ),
        migrations.AlterField(
            model_name='contentorder',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('review_pending', 'در انتظار ویراش'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.RemoveField(
            model_name='contentdelivery',
            name='files',
        ),
        migrations.DeleteModel(
            name='ContentDeliveryFile',
        ),
    ]
