# Generated by Django 6.0.2 on 2026-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='core_catego_parent__68b602_idx',
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='آیکون'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='core_catego_is_acti_26a709_idx'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
