# Generated by Django 6.0.2 on 2026-07-26 05:26

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('content_team', '0001_initial'),
        ('influencers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره فاکتور')),
                ('base_influencer_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه ناشران')),
                ('base_content_cost', models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه تولید محتوا')),
                ('base_commission', models.PositiveBigIntegerField(default=0, verbose_name='کمیسیون پایه پلتفرم')),
                ('influencer_discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف ناشران')),
                ('content_discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف تولید محتوا')),
                ('platform_discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف پلتفرم')),
                ('influencer_cost', models.PositiveBigIntegerField(verbose_name='هزینه نهایی اینفلوئنسر')),
                ('content_cost', models.PositiveBigIntegerField(verbose_name='هزینه نهایی تولید محتوا')),
                ('commission', models.PositiveBigIntegerField(verbose_name='کمیسیون نهایی پلتفرم')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='جمع کل تخفیف')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='مبلغ کل')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='پرداخت شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='campaigns.campaign', verbose_name='کمپین')),
            ],
            options={
                'verbose_name': 'فاکتور کمپین',
                'verbose_name_plural': 'فاکتورهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('scope', models.CharField(choices=[('influencer', 'اینفلوئنسر'), ('content_team', 'تیم محتوا'), ('platform', 'پلتفرم')], max_length=20, verbose_name='نوع تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع مقدار تخفیف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='influencers.influencerchannel', verbose_name='اینفلوئنسر')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='content_team.contentteam', verbose_name='تیم محتوا')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('payment_method', models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('wallet', 'کیف پول')], max_length=20, verbose_name='روش پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='authority')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='ref id')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payment.campaigninvoice', verbose_name='فاکتور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField(default=0, verbose_name='موجودی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر'), ('team_payment', 'پرداخت به تیم تولید محتوا')], max_length=30, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='success', max_length=20, verbose_name='وضعیت')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.campaign', verbose_name='کمپین مرتبط')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.campaigninvoice', verbose_name='فاکتور مرتبط')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payment.payment', verbose_name='پرداخت مرتبط')),
                ('team_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='content_team.contentteammember', verbose_name='عضو تیم محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='payment_tra_user_id_01aff8_idx'), models.Index(fields=['type', 'status'], name='payment_tra_type_e0423a_idx')],
            },
        ),
    ]
