# Generated by Django 6.0.8 on 2026-08-21 21:30

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر'), ('team_payment', 'پرداخت به تیم تولید محتوا'), ('influencer_withdrawal', 'تسویه ناشر'), ('content_team_withdrawal', 'تسویه تیم محتوا')], max_length=30, verbose_name='نوع تراکنش'),
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('influencer', 'ناشر'), ('content_team', 'عضو تیم محتوا')], max_length=20, verbose_name='نوع حساب')),
                ('sheba_code', models.CharField(help_text='شماره شبا بدون IR', max_length=24, verbose_name='شماره شبا')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='نام بانک')),
                ('account_holder_name', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('is_default', models.BooleanField(default=False, verbose_name='حساب پیش\u200cفرض')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حساب بانکی',
                'verbose_name_plural': 'حساب\u200cهای بانکی',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sheba_code')},
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('withdrawal_type', models.CharField(choices=[('influencer', 'تسویه ناشر'), ('content_team', 'تسویه تیم محتوا')], max_length=20, verbose_name='نوع تسویه')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ درخواستی (تومان)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('processing', 'در حال پردازش'), ('completed', 'انجام شده'), ('rejected', 'رد شده'), ('cancelled', 'لغو شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='کد پیگیری')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('requested_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('processed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پردازش')),
                ('completed_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='payment.bankaccount', verbose_name='حساب بانکی مقصد')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_requests', to='payment.transaction', verbose_name='تراکنش مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست تسویه',
                'verbose_name_plural': 'درخواست\u200cهای تسویه',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payment_wit_user_id_a02d11_idx'), models.Index(fields=['status', '-requested_at'], name='payment_wit_status_6136a2_idx')],
            },
        ),
    ]
