# Generated by Django 6.0.8 on 2026-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninvoice',
            name='commission_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات کمیسیون پلتفرم'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='content_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات هزینه تولید محتوا'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='influencer_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات هزینه ناشران'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='total_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع کل مالیات بر ارزش افزوده'),
        ),
    ]
