# Generated by Django 6.0.8 on 2026-09-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_transaction_type_bankaccount_withdrawalrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_type',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='تأیید شده'),
        ),
    ]
