# Generated by Django 6.0.8 on 2026-09-02 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bank'),
        ('payment', '0003_remove_bankaccount_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.bank', verbose_name='بانک'),
        ),
    ]
