# Generated by Django 6.0.8 on 2026-09-07 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_bankaccount_bank_name_bankaccount_bank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['tracking_code'], name='payment_wit_trackin_e600f5_idx'),
        ),
    ]
