# Generated by Django 6.0.8 on 2026-09-08 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_team', '0003_alter_contentorder_status'),
        ('payment', '0005_withdrawalrequest_payment_wit_trackin_e600f5_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='base_influencer_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='influencer_cost',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='influencer_discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='influencer_vat',
        ),
        migrations.AddField(
            model_name='invoice',
            name='content_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='content_team.contentorder', verbose_name='سفارش محتوا'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('campaign', 'فاکتور کمپین'), ('wallet', 'فاکتور شارژ کیف پول'), ('content_order', 'فاکتور سفارش محتوا')], default='campaign', max_length=20, verbose_name='نوع فاکتور'),
        ),
    ]
