# Generated by Django 6.0.8 on 2026-09-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_invoice_base_influencer_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر'), ('team_payment', 'پرداخت به تیم تولید محتوا'), ('content_order_payment', 'پرداخت سفارش تولید محتوا'), ('content_order_refund', 'بازگشت وجه سفارش محتوا'), ('influencer_withdrawal', 'تسویه ناشر'), ('content_team_withdrawal', 'تسویه تیم محتوا')], max_length=30, verbose_name='نوع تراکنش'),
        ),
    ]
