# Generated by Django 6.0.8 on 2026-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='base_influencer_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه اینفلوئنسرها'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='influencer_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه نهایی اینفلوئنسرها'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='influencer_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف اینفلوئنسرها'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='influencer_vat',
            field=models.PositiveBigIntegerField(default=0, verbose_name='مالیات هزینه اینفلوئنسرها'),
        ),
    ]
