# Generated by Django 6.0.8 on 2026-09-11 21:50

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_invoice_base_influencer_cost_invoice_influencer_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_share_from_pool', models.PositiveSmallIntegerField(default=60, help_text='درصدی از استخر ۶۰٪ که به مدیرعامل می\u200cرسد (پیش\u200cفرض: ۶۰)', verbose_name='سهم مدیرعامل از استخر')),
                ('developer_share_from_pool', models.PositiveSmallIntegerField(default=40, help_text='درصدی از استخر ۶۰٪ که به توسعه\u200cدهنده می\u200cرسد (پیش\u200cفرض: ۴۰)', verbose_name='سهم توسعه\u200cدهنده از استخر')),
                ('publish_manager_share', models.PositiveSmallIntegerField(default=30, help_text='درصد از کل کمیسیون وقتی فقط نشر داریم', verbose_name='سهم مدیر نشر (فقط نشر)')),
                ('content_manager_share', models.PositiveSmallIntegerField(default=30, help_text='درصد از کل کمیسیون وقتی فقط سفارش محتوا داریم', verbose_name='سهم مدیر محتوا (فقط محتوا)')),
                ('mixed_publish_manager_share', models.PositiveSmallIntegerField(default=15, help_text='درصد از کل کمیسیون وقتی هم نشر و هم محتوا داریم', verbose_name='سهم مدیر نشر (ترکیبی)')),
                ('mixed_content_manager_share', models.PositiveSmallIntegerField(default=15, help_text='درصد از کل کمیسیون وقتی هم نشر و هم محتوا داریم', verbose_name='سهم مدیر محتوا (ترکیبی)')),
                ('regional_manager_share', models.PositiveSmallIntegerField(default=5, help_text='درصد از کل کمیسیون که به مدیر استانی می\u200cرسد', verbose_name='سهم مدیر استانی')),
                ('is_active', models.BooleanField(default=True, help_text='فقط یک رکورد می\u200cتواند فعال باشد', verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخرین ویرایش\u200cکننده')),
            ],
            options={
                'verbose_name': 'تنظیمات کمیسیون',
                'verbose_name_plural': 'تنظیمات کمیسیون',
                'ordering': ['-updated_at'],
            },
        ),
    ]
