# Generated by Django 6.0.8 on 2026-09-12 09:27

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_commissionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commission_paid_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='زمانی که کمیسیون بین نقش\u200cهای سازمانی تقسیم شد', null=True, verbose_name='زمان واریز کمیسیون'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر'), ('team_payment', 'پرداخت به تیم تولید محتوا'), ('content_order_payment', 'پرداخت سفارش تولید محتوا'), ('content_order_refund', 'بازگشت وجه سفارش محتوا'), ('influencer_withdrawal', 'تسویه ناشر'), ('content_team_withdrawal', 'تسویه تیم محتوا'), ('commission_ceo', 'کمیسیون مدیرعامل'), ('commission_developer', 'کمیسیون توسعه\u200cدهنده'), ('commission_publish_manager', 'کمیسیون مدیر نشر'), ('commission_content_manager', 'کمیسیون مدیر محتوا'), ('commission_regional_manager', 'کمیسیون مدیر استانی')], max_length=30, verbose_name='نوع تراکنش'),
        ),
    ]
