# Generated by Django 6.0.8 on 2026-09-13 20:47

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_invoice_commission_paid_at_alter_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ceo_amount', models.PositiveBigIntegerField(default=0, verbose_name='سهم مدیرعامل')),
                ('developer_amount', models.PositiveBigIntegerField(default=0, verbose_name='سهم توسعه\u200cدهنده')),
                ('publish_manager_amount', models.PositiveBigIntegerField(default=0, verbose_name='سهم مدیر نشر')),
                ('content_manager_amount', models.PositiveBigIntegerField(default=0, verbose_name='سهم مدیر محتوا')),
                ('regional_manager_amount', models.PositiveBigIntegerField(default=0, verbose_name='سهم مدیر استانی')),
                ('site_maintenance_amount', models.PositiveBigIntegerField(default=0, verbose_name='هزینه نگهداری سایت')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='درصدهای تنظیمات در لحظه واریز', verbose_name='اسنپ\u200cشات تنظیمات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_split', to='payment.invoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'تسهیم کمیسیون',
                'verbose_name_plural': 'تسهیم\u200cهای کمیسیون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CommissionSetting',
        ),
        migrations.AddIndex(
            model_name='commissionsplit',
            index=models.Index(fields=['created_at'], name='payment_com_created_5c8148_idx'),
        ),
    ]
