# Generated by Django 6.0.8 on 2026-08-20 07:52

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='مثال: @example یا t.me/example', max_length=100, verbose_name='آیدی کانال/پیج')),
                ('channel_name', models.CharField(help_text='مثال: خبرگزاری فارس', max_length=100, verbose_name='نام کانال/پیج')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[500, 500], upload_to='influencers/channels_avatar', verbose_name='تصویر پروفایل کانال یا پیج')),
                ('qr_code', models.ImageField(blank=True, help_text='QR Code برای اشتراک\u200cگذاری پروفایل کانال', null=True, upload_to='influencers/qr_codes/', verbose_name='QR Code')),
                ('bio', models.TextField(blank=True, help_text='توضیحات مختصر درباره کانال، موضوع محتوا، مخاطبان هدف و ...', max_length=800, null=True, verbose_name='درباره کانال')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس کانال')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فالوور/مشترک')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید کانال')),
                ('verification_code_created_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تأیید')),
                ('verification_failed_attempts', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق تأیید')),
                ('rejected_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان رد شدن کانال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_channel', to='core.category', verbose_name='دسته\u200cبندی محتوایی')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_channels', to='core.platform', verbose_name='پلتفرم')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='core.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت به تومان', max_digits=12, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_rates', to='core.adtype', verbose_name='نوع تبلیغ')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='influencers.channel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'نرخ خدمت',
                'verbose_name_plural': 'نرخ خدمات',
                'ordering': ['ad_type'],
                'unique_together': {('channel', 'ad_type')},
            },
        ),
        migrations.CreateModel(
            name='ChannelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('rejected', 'رد شد'), ('completed', 'انجام شد'), ('replaced', 'جایگزین شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('is_seen', models.BooleanField(default=False, verbose_name='دیده شده؟')),
                ('tracking_code', models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='کد ردیابی')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تسویه شده؟')),
                ('paid_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='دلیل رد سفارش')),
                ('rejected_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ رد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_bookings', to='campaigns.campaign', verbose_name='کمپین')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_bookings', to='influencers.channel', verbose_name='کانال اینفلوئنسر')),
                ('service_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_services', to='influencers.channelservicerate', verbose_name='تعرفه سرویس')),
            ],
            options={
                'verbose_name': 'رزرو کانال',
                'verbose_name_plural': 'رزرو کانال ها',
            },
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل ناشر',
                'verbose_name_plural': 'پروفایل ناشران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='influencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='influencers.influencerprofile', verbose_name='اینفلوئنسر'),
        ),
        migrations.CreateModel(
            name='ChannelReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='از 1 تا 5', verbose_name='امتیاز')),
                ('comment', models.TextField(max_length=500, verbose_name='نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_reviews', to='advertisers.advertiserprofile', verbose_name='تبلیغ دهنده')),
                ('campaign_booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='influencers.channelbooking', verbose_name='رزرو کمپین')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='influencers.channel', verbose_name='کانال اینفلوئنسر')),
            ],
            options={
                'verbose_name': 'بازخورد کانال',
                'verbose_name_plural': 'بازخورد کانال ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rating'], name='influencers_rating_3eaa66_idx'), models.Index(fields=['created_at'], name='influencers_created_30b1db_idx'), models.Index(fields=['channel', '-created_at'], name='influencers_channel_71c0d7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['platform'], name='influencers_platfor_2e78d7_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['province'], name='influencers_provinc_995998_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['category'], name='influencers_categor_6fab03_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['followers_count'], name='influencers_followe_eb5719_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('influencer', 'platform', 'channel_id')},
        ),
    ]
