# Generated by Django 6.0.2 on 2026-04-28 07:10

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('core', '0001_initial'),
        ('location', '0001_initial'),
        ('plat_form', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.URLField(help_text='لینک مستقیم پست منتشر شده', verbose_name='لینک پست')),
                ('screenshot', models.ImageField(upload_to='campaign_reports/screenshots/', verbose_name='اسکرین\u200cشات پست')),
                ('link_valid', models.BooleanField(default=False)),
                ('hashtag_match_percent', models.FloatField(default=0)),
                ('text_match_percent', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شد'), ('rejected', 'رد شد'), ('partial', 'تأیید جزئی')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='campaigns.campaigninfluencer', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'گزارش کمپین',
                'verbose_name_plural': 'گزارش\u200cهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='InfluencerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='اسم کامل کانال/پیج')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اینفلوئنسر',
                'verbose_name_plural': 'اینفلوئنسرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text='مثال: @example یا t.me/example', max_length=100, verbose_name='آیدی کانال/پیج')),
                ('channel_name', models.CharField(help_text='مثال: خبرگزاری فارس', max_length=100, verbose_name='نام کانال/پیج')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=90, scale=1, size=[500, 500], upload_to='influencers/channels_avatar', verbose_name='تصویر پروفایل کانال یا پیج')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس کانال')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='تعداد فالوور/مشترک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_channel', to='core.category', verbose_name='دسته\u200cبندی محتوایی')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='location.city', verbose_name='شهر')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_channels', to='plat_form.platform', verbose_name='پلتفرم')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencers', to='location.province', verbose_name='استان')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='influencers.influencerprofile', verbose_name='اینفلوئنسر')),
            ],
            options={
                'verbose_name': 'کانال اینفلوئنسر',
                'verbose_name_plural': 'کانال\u200cهای اینفلوئنسر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='از 1 تا 5', verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_reviews', to='advertisers.advertiserprofile', verbose_name='تبلیغ\u200cدهنده')),
                ('campaign_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='campaigns.campaigninfluencer', verbose_name='رزرو کمپین')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='influencers.influencerchannel', verbose_name='کانال اینفلوئنسر')),
            ],
            options={
                'verbose_name': 'نظر درباره اینفلوئنسر',
                'verbose_name_plural': 'نظرات درباره اینفلوئنسرها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfluencerServiceRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, help_text='قیمت به تومان', max_digits=12, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_rates', to='campaigns.adtype', verbose_name='نوع تبلیغ')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_rates', to='influencers.influencerchannel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'نرخ خدمت اینفلوئنسر',
                'verbose_name_plural': 'نرخ\u200cهای خدمات اینفلوئنسر',
                'ordering': ['ad_type'],
            },
        ),
        migrations.AddIndex(
            model_name='influencerchannel',
            index=models.Index(fields=['platform'], name='influencers_platfor_2b647c_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerchannel',
            index=models.Index(fields=['province'], name='influencers_provinc_ab9633_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerchannel',
            index=models.Index(fields=['city'], name='influencers_city_id_59294b_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerchannel',
            index=models.Index(fields=['category'], name='influencers_categor_d3cc9a_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerchannel',
            index=models.Index(fields=['followers_count'], name='influencers_followe_7074d3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='influencerchannel',
            unique_together={('influencer', 'platform', 'channel_id')},
        ),
        migrations.AddIndex(
            model_name='influencerreview',
            index=models.Index(fields=['rating'], name='influencers_rating_45cfb3_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerreview',
            index=models.Index(fields=['created_at'], name='influencers_created_214af5_idx'),
        ),
        migrations.AddIndex(
            model_name='influencerreview',
            index=models.Index(fields=['channel', '-created_at'], name='influencers_channel_0f8000_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='influencerservicerate',
            unique_together={('channel', 'ad_type')},
        ),
    ]
