# Generated by Django 6.0.2 on 2026-05-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='influencerchannel',
            name='influencers_city_id_59294b_idx',
        ),
        migrations.RemoveField(
            model_name='influencerchannel',
            name='city',
        ),
    ]
