# Generated by Django 6.0.2 on 2026-04-04 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaigninfluencer_is_seen'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.URLField(help_text='لینک مستقیم پست منتشر شده', verbose_name='لینک پست')),
                ('screenshot', models.ImageField(upload_to='campaign_reports/screenshots/', verbose_name='اسکرین\u200cشات پست')),
                ('link_valid', models.BooleanField(default=False)),
                ('hashtag_match_percent', models.FloatField(default=0)),
                ('text_match_percent', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شد'), ('rejected', 'رد شد'), ('partial', 'تأیید جزئی')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='campaigns.campaigninfluencer', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'گزارش کمپین',
                'verbose_name_plural': 'گزارش\u200cهای کمپین',
            },
        ),
    ]
