# Generated by Django 6.0.8 on 2026-08-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ['-created_at'], 'verbose_name': 'کانال', 'verbose_name_plural': 'کانال ها'},
        ),
        migrations.AlterModelOptions(
            name='channelbooking',
            options={'verbose_name': 'رزرو کانال', 'verbose_name_plural': 'رزرو کانال ها'},
        ),
        migrations.AlterModelOptions(
            name='channelreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'بازخورد کانال', 'verbose_name_plural': 'بازخورد کانال ها'},
        ),
        migrations.AlterModelOptions(
            name='channelservicerate',
            options={'ordering': ['ad_type'], 'verbose_name': 'نرخ خدمت', 'verbose_name_plural': 'نرخ خدمات'},
        ),
        migrations.AlterModelOptions(
            name='influencerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل ناشر', 'verbose_name_plural': 'پروفایل ناشران'},
        ),
        migrations.RemoveField(
            model_name='influencerprofile',
            name='full_name',
        ),
    ]
