# Generated by Django 6.0.2 on 2026-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
