# Generated by Django 6.0.2 on 2026-07-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='bale_channel_id',
            field=models.CharField(blank=True, help_text='آیدی عددی کانال برای ارسال مستقیم پست (مثلاً: -100123456789)', max_length=100, null=True, verbose_name='آیدی عددی کانال در بله'),
        ),
        migrations.AddField(
            model_name='influencerchannel',
            name='is_bot_admin',
            field=models.BooleanField(default=False, help_text='اگر کاربر ربات را به عنوان ادمین به کانال اضافه کرده باشد', verbose_name='ربات در کانال ادمین است؟'),
        ),
        migrations.AddField(
            model_name='influencerchannel',
            name='prefer_forward_in_pv',
            field=models.BooleanField(default=False, help_text='اگر True باشد، پست به پی\u200cوی کاربر ارسال می\u200cشود تا خودش فوروارد کند', verbose_name='ترجیح دریافت در پی\u200cوی به جای ارسال مستقیم'),
        ),
    ]
