# Generated by Django 6.0.2 on 2026-06-02 20:17

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('influencers', '0002_remove_influencerchannel_influencers_city_id_59294b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerchannel',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[500, 500], upload_to='influencers/channels_avatar', verbose_name='تصویر پروفایل کانال یا پیج'),
        ),
        migrations.AlterField(
            model_name='influencerreview',
            name='campaign_booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='campaigns.campaigninfluencer', verbose_name='رزرو کمپین'),
        ),
        migrations.AlterField(
            model_name='influencerreview',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='نظر'),
        ),
    ]
