# Generated by Django 6.0.2 on 2026-04-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('influencers', '0002_campaignreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerchannel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_channel', to='core.category', verbose_name='دسته\u200cبندی محتوایی'),
        ),
    ]
