# Generated by Django 6.0.2 on 2026-07-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_influencerchannel_bale_channel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerchannel',
            name='bale_channel_id',
        ),
        migrations.RemoveField(
            model_name='influencerchannel',
            name='is_bot_admin',
        ),
        migrations.RemoveField(
            model_name='influencerchannel',
            name='prefer_forward_in_pv',
        ),
    ]
