# Generated by Django 6.0.8 on 2026-08-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0002_alter_channel_options_alter_channelbooking_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='bio',
            field=models.TextField(blank=True, help_text='توضیحات مختصر درباره کانال، موضوع محتوا، مخاطبان هدف و ...', max_length=500, null=True, verbose_name='درباره کانال'),
        ),
    ]
