# Generated by Django 6.0.2 on 2026-07-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_remove_influencerchannel_bale_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='QR Code برای اشتراک\u200cگذاری پروفایل کانال', null=True, upload_to='influencers/qr_codes/', verbose_name='QR Code'),
        ),
    ]
