# Generated by Django 6.0.8 on 2026-08-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_channel_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='description',
        ),
        migrations.AlterField(
            model_name='channel',
            name='bio',
            field=models.TextField(blank=True, help_text='توضیحات مختصر درباره کانال، موضوع محتوا، مخاطبان هدف و ...', max_length=800, null=True, verbose_name='درباره کانال'),
        ),
    ]
