# Generated by Django 6.0.2 on 2026-06-07 21:25

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0003_alter_influencerchannel_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='کد تأیید کانال'),
        ),
        migrations.AddField(
            model_name='influencerchannel',
            name='verification_code_created_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان ایجاد کد تأیید'),
        ),
    ]
