# Generated by Django 6.0.2 on 2026-06-07 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0004_influencerchannel_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='verification_failed_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش\u200cهای ناموفق تأیید'),
        ),
    ]
