# Generated by Django 6.0.2 on 2026-06-08 08:08

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0005_influencerchannel_verification_failed_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='influencerchannel',
            name='rejected_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان رد شدن کانال'),
        ),
    ]
