# Generated by Django 6.0.2 on 2026-06-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_influencerchannel_rejected_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignreport',
            name='hashtag_match_percent',
        ),
        migrations.RemoveField(
            model_name='campaignreport',
            name='link_valid',
        ),
        migrations.RemoveField(
            model_name='campaignreport',
            name='text_match_percent',
        ),
        migrations.AddField(
            model_name='campaignreport',
            name='auto_check_details',
            field=models.JSONField(blank=True, default=dict, verbose_name='جزئیات بررسی خودکار'),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='post_link',
            field=models.URLField(verbose_name='لینک پست'),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='screenshot',
            field=models.ImageField(upload_to='campaign_reports/screenshots/'),
        ),
        migrations.AlterField(
            model_name='campaignreport',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شد'), ('rejected', 'رد شد')], default='pending', max_length=20, verbose_name='وضعیت بررسی'),
        ),
    ]
