# Generated by Django 6.0.2 on 2026-07-26 08:52

import django.utils.timezone
import django_jalali.db.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('login', 'ورود'), ('register', 'ثبت\u200cنام'), ('verify', 'تایید عمومی')], default='verify', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('verified', 'تایید شده'), ('expired', 'منقضی شده')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('expires_at', django_jalali.db.models.jDateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('api_status_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'رمز یکبار مصرف',
                'verbose_name_plural': 'رمز های یکبار مصرف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('bale_chat_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه ربات بله')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=110, null=True, verbose_name='ایمیل')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام مستعار')),
                ('avatar', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=1, size=[500, 500], upload_to='avatars/', verbose_name='تصویر پروفایل')),
                ('sheba_code', models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_regional_manager', models.BooleanField(default=False, help_text='اگر فعال باشد، کاربر فقط دسترسی به استان خودش را دارد', verbose_name='مدیر استانی')),
                ('date_joined', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-created_at'],
            },
        ),
    ]
