# Generated by Django 6.0.2 on 2026-04-05 08:58

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('campaigns', '0008_campaigninfluencer_is_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ')),
                ('type', models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('commission', 'کمیسیون پلتفرم')], max_length=30, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='success', max_length=20, verbose_name='وضعیت')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='شماره مرجع')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.campaign', verbose_name='کمپین مرتبط')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.campaigninvoice', verbose_name='فاکتور مرتبط')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='campaigns.payment', verbose_name='پرداخت مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-created_at'], name='accounts_tr_user_id_cfd094_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type', 'status'], name='accounts_tr_type_cf35be_idx'),
        ),
    ]
