# Generated by Django 6.0.2 on 2026-07-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['phone_number', 'status'], name='accounts_ot_phone_n_809ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='otprequest',
            index=models.Index(fields=['expires_at'], name='accounts_ot_expires_e80723_idx'),
        ),
    ]
