# Generated by Django 6.0.2 on 2026-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_transaction_delete_wallettransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر')], max_length=30, verbose_name='نوع تراکنش'),
        ),
    ]
