# Generated by Django 6.0.2 on 2026-07-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='accounts_tr_user_id_cfd094_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='accounts_tr_type_cf35be_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='team_member',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
