# Generated by Django 6.0.8 on 2026-09-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_regional_manager',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('none', 'بدون نقش'), ('ceo', 'مدیرعامل'), ('developer', 'توسعه\u200cدهنده'), ('content_manager', 'مدیر تولید محتوا'), ('publish_manager', 'مدیر نشر'), ('regional_manager', 'مدیر استانی')], db_index=True, default='none', help_text='نقش کاربر در پنل پشتیبانی و دسترسی\u200cها', max_length=30, verbose_name='نقش سازمانی'),
        ),
    ]
