# Generated by Django 6.0.2 on 2026-05-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bale_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='شناسه ربات بله'),
        ),
    ]
