# Generated by Django 6.0.2 on 2026-04-07 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_transaction_type'),
        ('content_team', '0005_remove_contentteammember_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='team_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='content_team.contentteammember', verbose_name='عضو تیم محتوا'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف پول'), ('withdraw', 'برداشت از کیف پول'), ('campaign_payment', 'پرداخت کمپین'), ('campaign_refund', 'بازگشت وجه کمپین'), ('gateway_payment', 'پرداخت مستقیم از درگاه'), ('gateway_refund', 'بازگشت وجه از درگاه'), ('influencer_payment', 'پرداخت به ناشر'), ('team_payment', 'پرداخت به تیم تولید محتوا'), ('team_member_payout', 'تسویه با عضو تیم')], max_length=30, verbose_name='نوع تراکنش'),
        ),
    ]
