# Generated by Django 6.0.2 on 2026-07-23 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_transaction_accounts_tr_user_id_cfd094_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'رمز یکبار مصرف', 'verbose_name_plural': 'رمز های یکبار مصرف'},
        ),
    ]
