# Generated by Django 6.0.2 on 2026-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_transaction_team_member_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sheba_code',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا'),
        ),
    ]
