# Generated by Django 6.0.2 on 2026-04-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_transaction_type'),
        ('location', '0002_province_latitude_province_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_regional_manager',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، کاربر فقط دسترسی به استان خودش را دارد', verbose_name='مدیر استانی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='managed_province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to='location.province', verbose_name='استان تحت مدیریت'),
        ),
    ]
