# Generated by Django 6.0.2 on 2026-04-20 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_is_regional_manager_and_more'),
        ('location', '0002_province_latitude_province_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='managed_province',
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='location.province', verbose_name='استان'),
        ),
    ]
