# Generated by Django 6.0.2 on 2026-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_managed_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('type', models.CharField(choices=[('login', 'ورود'), ('register', 'ثبت\u200cنام'), ('verify', 'تایید عمومی')], default='verify', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('verified', 'تایید شده'), ('expired', 'منقضی شده')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('api_status_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'status'], name='accounts_ot_phone_n_809ae5_idx'), models.Index(fields=['expires_at'], name='accounts_ot_expires_e80723_idx')],
            },
        ),
    ]
