# Generated by Django 6.0.2 on 2026-04-24 09:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='expires_at',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
