# Generated by Django 6.0.2 on 2026-07-26 08:52

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='دسته بندی')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'دسته بندی بلاگ',
                'verbose_name_plural': 'دسته بندی های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='برچسب')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'برچسب بلاگ',
                'verbose_name_plural': 'برچسب های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='تصویر')),
                ('read_time', models.PositiveIntegerField(help_text='زمان تخمینی مطالعه بلاگ به دقیقه', verbose_name='زمان مطالعه (دقیقه)')),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Published'), ('-1', 'Rejected')], default='0', max_length=2, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.blogcategory', verbose_name='دسته بندی')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtags', verbose_name='برچسب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True, verbose_name='نام')),
                ('content', models.TextField(max_length=1500, verbose_name='متن')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('is_active', models.BooleanField(default=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.postcomments', verbose_name='پاسخ به')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='پست')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر پست',
                'verbose_name_plural': 'نظرات پست',
                'ordering': ['-created_at'],
            },
        ),
    ]
