# Generated by Django 6.0.2 on 2026-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('slug', models.SlugField(max_length=160, verbose_name='اسلاگ')),
                ('description', models.TextField(max_length=750, verbose_name='توضیحات')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platform/logos', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
            ],
            options={
                'verbose_name': 'پلتفرم',
                'verbose_name_plural': 'پلتفرم ها',
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
