# Generated by Django 6.0.2 on 2026-03-22 10:00

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('plat_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_cost', models.PositiveBigIntegerField(verbose_name='هزینه اینفلوئنسر')),
                ('content_cost', models.PositiveBigIntegerField(verbose_name='هزینه تولید محتوا')),
                ('commission', models.PositiveBigIntegerField(verbose_name='کمیسیون پلتفرم')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف')),
                ('total_amount', models.PositiveBigIntegerField(verbose_name='مبلغ کل')),
                ('payable_amount', models.PositiveBigIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('is_paid', models.BooleanField(db_index=True, default=False, verbose_name='پرداخت شده')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'فاکتور کمپین',
                'verbose_name_plural': 'فاکتورهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع محتوا')),
                ('slug', models.SlugField(verbose_name='شناسه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع محتوا',
                'verbose_name_plural': 'انواع محتوا',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('scope', models.CharField(choices=[('influencer', 'اینفلوئنسر'), ('content_team', 'تیم محتوا'), ('platform', 'پلتفرم')], max_length=20, verbose_name='نوع تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], max_length=20, verbose_name='نوع مقدار تخفیف')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('expires_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='مبلغ')),
                ('authority', models.CharField(blank=True, max_length=255, verbose_name='authority')),
                ('ref_id', models.CharField(blank=True, max_length=255, verbose_name='ref id')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام نوع تبلیغ')),
                ('slug', models.SlugField(verbose_name='شناسه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_types', to='plat_form.platform', verbose_name='پلتفرم')),
            ],
            options={
                'verbose_name': 'نوع تبلیغ',
                'verbose_name_plural': 'انواع تبلیغ',
                'ordering': ['platform', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کمپین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='زمان شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('running', 'در حال اجرا'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('ad_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.adtype', verbose_name='نوع تبلیغ')),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='advertisers.advertiserprofile', verbose_name='تبلیغ دهنده')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='plat_form.platform', verbose_name='پلتفرم')),
            ],
            options={
                'verbose_name': 'کمپین',
                'verbose_name_plural': 'کمپین\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='campaign/content_media/', verbose_name='عکس یا ویدیو')),
                ('caption', models.TextField(verbose_name='متن کامل تبلیغ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مقصد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات برای اینفلوئنسر')),
                ('utm_enabled', models.BooleanField(default=False, verbose_name='فعال سازی UTM')),
                ('utm_source', models.CharField(blank=True, max_length=150, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=150, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=150, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=150, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=150, verbose_name='utm_term')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='campaigns.campaign', verbose_name='کمپین')),
            ],
            options={
                'verbose_name': 'محتوای کمپین',
                'verbose_name_plural': 'محتواهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='CampaignInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت نهایی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('rejected', 'رد شد'), ('completed', 'انجام شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_bookings', to='campaigns.campaign', verbose_name='کمپین')),
            ],
            options={
                'verbose_name': 'رزرو اینفلوئنسر',
                'verbose_name_plural': 'رزروهای اینفلوئنسر',
            },
        ),
    ]
