# Generated by Django 6.0.2 on 2026-07-26 14:48

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_rejection_count', models.PositiveIntegerField(default=0, verbose_name='تعداد رد شده توسط اینفلوئنسرها')),
                ('content_team_rejected', models.BooleanField(default=False, verbose_name='تیم محتوا رد کرده؟')),
                ('replacement_mode', models.BooleanField(default=False, verbose_name='حالت انتخاب جایگزین فعال است؟')),
                ('name', models.CharField(max_length=255, verbose_name='نام کمپین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('start_date', django_jalali.db.models.jDateField(verbose_name='زمان شروع')),
                ('end_date', django_jalali.db.models.jDateField(verbose_name='زمان پایان')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('running', 'در حال اجرا'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده'), ('revision_needed', 'نیاز به اصلاح')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_free', models.BooleanField(default=False, verbose_name='عام\u200cالمنفعه')),
                ('discount_amount', models.PositiveBigIntegerField(default=0, verbose_name='مقدار تخفیف')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('approved_at', django_jalali.db.models.jDateTimeField(blank=True, help_text='زمانی که کمپین از وضعیت pending به approved تغییر کرد', null=True, verbose_name='زمان تایید')),
            ],
            options={
                'verbose_name': 'کمپین',
                'verbose_name_plural': 'کمپین\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کلیک کمپین',
                'verbose_name_plural': 'کلیک های کمپین',
            },
        ),
        migrations.CreateModel(
            name='CampaignContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='campaign/content_media/', verbose_name='عکس یا ویدیو')),
                ('caption', models.TextField(verbose_name='متن کامل تبلیغ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک مقصد')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات برای اینفلوئنسر')),
                ('utm_enabled', models.BooleanField(default=False, verbose_name='فعال سازی UTM')),
                ('utm_source', models.CharField(blank=True, max_length=150, verbose_name='utm_source')),
                ('utm_medium', models.CharField(blank=True, max_length=150, verbose_name='utm_medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=150, verbose_name='utm_campaign')),
                ('utm_content', models.CharField(blank=True, max_length=150, verbose_name='utm_content')),
                ('utm_term', models.CharField(blank=True, max_length=150, verbose_name='utm_term')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
            ],
            options={
                'verbose_name': 'محتوای کمپین',
                'verbose_name_plural': 'محتواهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='CampaignReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_link', models.URLField(verbose_name='لینک پست')),
                ('screenshot', models.ImageField(upload_to='campaign_reports/screenshots/')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شد'), ('rejected', 'رد شد')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('auto_check_details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات بررسی خودکار')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'گزارش کمپین',
                'verbose_name_plural': 'گزارش\u200cهای کمپین',
            },
        ),
        migrations.CreateModel(
            name='CampaignTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لینک ردیابی',
                'verbose_name_plural': 'لینک های ردیابی',
            },
        ),
    ]
