# Generated by Django 6.0.2 on 2026-07-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('content_team', '0001_initial'),
        ('core', '0001_initial'),
        ('influencers', '0001_initial'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='content_team.contentservicetype', verbose_name='سرویس تولید محتوا'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_team_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_team_campaigns', to='payment.coupon', verbose_name='کد تخفیف تیم محتوا'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_campaigns', to='payment.coupon', verbose_name='کد تخفیف اینفلوئنسر'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='core.platform', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_campaigns', to='payment.coupon', verbose_name='کد تخفیف پلتفرم'),
        ),
        migrations.AddField(
            model_name='campaigncontent',
            name='campaign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='campaigns.campaign', verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influencer_bookings', to='campaigns.campaign', verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_bookings', to='influencers.influencerchannel', verbose_name='کانال اینفلوئنسر'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='service_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_services', to='influencers.influencerservicerate', verbose_name='تعرفه سرویس'),
        ),
        migrations.AddField(
            model_name='campaigntrackinglink',
            name='campaign_influencer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='campaigns.campaigninfluencer'),
        ),
        migrations.AddField(
            model_name='campaignclick',
            name='tracking_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='campaigns.campaigntrackinglink'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='platform',
            field=models.ManyToManyField(related_name='content_types', to='core.platform', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='campaigns.contenttype', verbose_name='نوع محتوا'),
        ),
        migrations.AlterUniqueTogether(
            name='adtype',
            unique_together={('platform', 'slug')},
        ),
        migrations.AddIndex(
            model_name='campaignclick',
            index=models.Index(fields=['tracking_link', 'ip_address'], name='campaigns_c_trackin_ea6861_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignclick',
            index=models.Index(fields=['created_at'], name='campaigns_c_created_a61d76_idx'),
        ),
    ]
