# Generated by Django 6.0.8 on 2026-08-05 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name': 'کمپین', 'verbose_name_plural': 'کمپین ها'},
        ),
        migrations.AlterModelOptions(
            name='campaignclick',
            options={'verbose_name': 'کلیک', 'verbose_name_plural': 'کلیک ها'},
        ),
        migrations.AlterModelOptions(
            name='campaigncontent',
            options={'verbose_name': 'محتوای کمپین', 'verbose_name_plural': 'محتوا های کمپین'},
        ),
    ]
