# Generated by Django 6.0.2 on 2026-04-28 07:59

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='end_date',
            field=django_jalali.db.models.jDateField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_date',
            field=django_jalali.db.models.jDateField(verbose_name='زمان شروع'),
        ),
    ]
