# Generated by Django 6.0.2 on 2026-03-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
        ('content_team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='content_team.contentservicetype', verbose_name='سرویس تولید محتوا'),
        ),
    ]
