# Generated by Django 6.0.8 on 2026-09-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='discount_amount',
        ),
    ]
