# Generated by Django 6.0.2 on 2026-06-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که کمپین از وضعیت pending به approved تغییر کرد', null=True, verbose_name='زمان تایید'),
        ),
    ]
