# Generated by Django 6.0.2 on 2026-06-28 17:17

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='content_team_rejected',
            field=models.BooleanField(default=False, verbose_name='تیم محتوا رد کرده؟'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencer_rejection_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد رد شده توسط اینفلوئنسرها'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='replacement_mode',
            field=models.BooleanField(default=False, verbose_name='حالت انتخاب جایگزین فعال است؟'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='rejected_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ رد'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد سفارش'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('running', 'در حال اجرا'), ('completed', 'تمام شده'), ('cancelled', 'لغو شده'), ('revision_needed', 'نیاز به اصلاح')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='campaigninfluencer',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('rejected', 'رد شد'), ('completed', 'انجام شد'), ('replaced', 'جایگزین شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
