# Generated by Django 6.0.2 on 2026-06-07 08:32

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_approved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='approved_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, help_text='زمانی که کمپین از وضعیت pending به approved تغییر کرد', null=True, verbose_name='زمان تایید'),
        ),
    ]
