# Generated by Django 6.0.2 on 2026-03-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_content_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='icon',
            field=models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً: fa-video)', max_length=50, verbose_name='آیکون'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='contenttype',
            name='icon',
            field=models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً: fa-video)', max_length=100, verbose_name='آیکون'),
        ),
    ]
