# Generated by Django 6.0.2 on 2026-07-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_content_team_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninvoice',
            name='base_commission',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کمیسیون پایه'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='base_content_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه تولید محتوا'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='total_additional_paid',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کل مبلغ پرداختی اضافی'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='total_refunded',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کل مبلغ برگشتی'),
        ),
    ]
