# Generated by Django 6.0.2 on 2026-03-28 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_adtype_icon_contenttype_description_contenttype_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True, unique=True, verbose_name='کد ردیابی'),
        ),
        migrations.CreateModel(
            name='CampaignTrackingLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign_influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_link', to='campaigns.campaigninfluencer')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='campaigns.campaigntrackinglink')),
            ],
            options={
                'indexes': [models.Index(fields=['ip_address'], name='campaigns_c_ip_addr_303ad2_idx'), models.Index(fields=['created_at'], name='campaigns_c_created_a61d76_idx')],
            },
        ),
    ]
