# Generated by Django 6.0.2 on 2026-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='کمپین رایگان (عام\u200cالمنفعه)'),
        ),
    ]
