# Generated by Django 6.0.2 on 2026-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaigninvoice_base_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='base_content_cost',
        ),
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='total_additional_paid',
        ),
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='total_refunded',
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='cancelled_content_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه تولید محتوای رد شده'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='confirmed_content_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه تولید محتوای تایید شده'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='final_commission',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کمیسیون نهایی'),
        ),
    ]
