# Generated by Django 6.0.2 on 2026-07-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_remove_campaigninvoice_base_content_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='base_commission',
        ),
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='cancelled_content_cost',
        ),
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='confirmed_content_cost',
        ),
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='final_commission',
        ),
    ]
