# Generated by Django 6.0.2 on 2026-03-29 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigninfluencer_tracking_code_and_more'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignclick',
            options={'verbose_name': 'کلیک کمپین', 'verbose_name_plural': 'کلیک های کمپین'},
        ),
        migrations.AlterModelOptions(
            name='campaigntrackinglink',
            options={'verbose_name': 'لینک ردیابی', 'verbose_name_plural': 'لینک های ردیابی'},
        ),
        migrations.RemoveIndex(
            model_name='campaignclick',
            name='campaigns_c_ip_addr_303ad2_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='influencer',
        ),
        migrations.AddField(
            model_name='coupon',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='influencers.influencerchannel', verbose_name='اینفلوئنسر'),
        ),
        migrations.AddIndex(
            model_name='campaignclick',
            index=models.Index(fields=['tracking_link', 'ip_address'], name='campaigns_c_trackin_ea6861_idx'),
        ),
    ]
