# Generated by Django 6.0.2 on 2026-06-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='عام\u200cالمنفعه'),
        ),
    ]
