# Generated by Django 6.0.2 on 2026-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaignclick_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('gateway', 'درگاه پرداخت'), ('wallet', 'کیف پول')], default=None, max_length=20, verbose_name='روش پرداخت'),
            preserve_default=False,
        ),
    ]
