# Generated by Django 6.0.2 on 2026-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_remove_campaigninvoice_base_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninvoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره فاکتور'),
        ),
    ]
