# Generated by Django 6.0.2 on 2026-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='is_seen',
            field=models.BooleanField(default=False, verbose_name='دیده شده؟'),
        ),
    ]
