# Generated by Django 6.0.2 on 2026-07-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaigninvoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninvoice',
            name='base_commission',
            field=models.PositiveBigIntegerField(default=0, verbose_name='کمیسیون پایه پلتفرم'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='base_content_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه تولید محتوا'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='base_influencer_cost',
            field=models.PositiveBigIntegerField(default=0, verbose_name='هزینه پایه ناشران'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='content_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف تولید محتوا'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='influencer_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف ناشران'),
        ),
        migrations.AddField(
            model_name='campaigninvoice',
            name='platform_discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='تخفیف پلتفرم'),
        ),
        migrations.AlterField(
            model_name='campaigninvoice',
            name='commission',
            field=models.PositiveBigIntegerField(verbose_name='کمیسیون نهایی پلتفرم'),
        ),
        migrations.AlterField(
            model_name='campaigninvoice',
            name='content_cost',
            field=models.PositiveBigIntegerField(verbose_name='هزینه نهایی تولید محتوا'),
        ),
        migrations.AlterField(
            model_name='campaigninvoice',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0, verbose_name='جمع کل تخفیف'),
        ),
        migrations.AlterField(
            model_name='campaigninvoice',
            name='influencer_cost',
            field=models.PositiveBigIntegerField(verbose_name='هزینه نهایی اینفلوئنسر'),
        ),
    ]
