# Generated by Django 6.0.2 on 2026-04-07 06:45

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaigninfluencer_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigninfluencer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده به اینفلوئنسر'),
        ),
        migrations.AddField(
            model_name='campaigninfluencer',
            name='paid_at',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت'),
        ),
    ]
