# Generated by Django 6.0.2 on 2026-07-23 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaigninvoice_base_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigninvoice',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='team',
        ),
    ]
