# Generated by Django 6.0.2 on 2026-07-23 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_transaction_accounts_tr_user_id_cfd094_idx_and_more'),
        ('campaigns', '0009_remove_campaigninvoice_campaign_and_more'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='content_team_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_team_campaigns', to='payment.coupon', verbose_name='کد تخفیف تیم محتوا'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='platform_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_campaigns', to='payment.coupon', verbose_name='کد تخفیف پلتفرم'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='influencer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_campaigns', to='payment.coupon', verbose_name='کد تخفیف اینفلوئنسر'),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='CampaignInvoice',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
