# Generated by Django 6.0.2 on 2026-04-16 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaigninfluencer_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='coupon',
        ),
        migrations.AddField(
            model_name='campaign',
            name='content_team_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_team_campaigns', to='campaigns.coupon', verbose_name='کد تخفیف تیم محتوا'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='influencer_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencer_campaigns', to='campaigns.coupon', verbose_name='کد تخفیف اینفلوئنسر'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='platform_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_campaigns', to='campaigns.coupon', verbose_name='کد تخفیف پلتفرم'),
        ),
    ]
