# Generated by Django 6.0.2 on 2026-04-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_remove_campaign_coupon_campaign_content_team_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninfluencer',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'پذیرفته شد'), ('rejected', 'رد شد'), ('running', 'در حال اجرا'), ('completed', 'انجام شد')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
    ]
