# Generated by Django 6.0.2 on 2026-04-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0011_alter_campaigninfluencer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninfluencer',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='تسویه شده؟'),
        ),
    ]
