# Generated by Django 6.0.8 on 2026-08-30 19:36

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=15, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('cancelled', 'لغو شده'), ('completed', 'تمام شده')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, help_text='فقط برای ادمین قابل مشاهده است', null=True, verbose_name='یادداشت ادمین')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_requests', to='tickets.ticketcategory', verbose_name='موضوع')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'درخواست تماس',
                'verbose_name_plural': 'درخواست\u200cهای تماس',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='tickets_con_status_50f7b5_idx'), models.Index(fields=['phone'], name='tickets_con_phone_32d4df_idx')],
            },
        ),
    ]
