# Generated by Django 6.0.2 on 2026-05-28 13:52

import django.db.models.deletion
import django_jalali.db.models
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisers', '0001_initial'),
        ('content_team', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='کد یکتا برای استفاده در برنامه، مثال: bronze, silver, gold', unique=True, verbose_name='کد سطح')),
                ('name', models.CharField(help_text='نام نمایشی، مثال: برنزی، نقره\u200cای، طلایی', max_length=100, verbose_name='نام سطح')),
                ('min_points', models.PositiveIntegerField(default=0, help_text='حداقل امتیاز مورد نیاز برای کسب این سطح', verbose_name='حداقل امتیاز')),
                ('icon', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='تصویر مربعی ۶۴x۶۴ پیکسل (اختیاری)', keep_meta=False, null=True, quality=90, scale=1, size=[64, 64], upload_to='badges/icons/', verbose_name='آیکون یا تصویر سطح')),
                ('description', models.TextField(blank=True, help_text='توضیحات این سطح (اختیاری)', verbose_name='توضیحات')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='عدد کوچک\u200cتر = سطح پایین\u200cتر', verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'نشان / سطح',
                'verbose_name_plural': 'نشان\u200cها / سطوح',
                'ordering': ['order', 'min_points'],
            },
        ),
        migrations.CreateModel(
            name='AdvertiserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='کل امتیازات')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='advertisers.advertiserprofile', verbose_name='تبلیغ\u200cدهنده')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='نشان فعلی')),
                ('highest_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='بالاترین نشان کسب شده')),
            ],
            options={
                'verbose_name': 'امتیاز تبلیغ\u200cدهنده',
                'verbose_name_plural': 'امتیازات تبلیغ\u200cدهندگان',
            },
        ),
        migrations.CreateModel(
            name='ChannelScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='کل امتیازات')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='نشان فعلی')),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='influencers.influencerchannel', verbose_name='کانال اینفلوئنسر')),
                ('highest_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='بالاترین نشان کسب شده')),
            ],
            options={
                'verbose_name': 'امتیاز کانال',
                'verbose_name_plural': 'امتیازات کانال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TeamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='کل امتیازات')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='نشان فعلی')),
                ('highest_badge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gamification.badge', verbose_name='بالاترین نشان کسب شده')),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='content_team.contentteam', verbose_name='تیم تولید محتوا')),
            ],
            options={
                'verbose_name': 'امتیاز تیم',
                'verbose_name_plural': 'امتیازات تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('points_changed', models.IntegerField(verbose_name='تغییرات امتیاز')),
                ('action_key', models.CharField(max_length=100, verbose_name='کلید اکشن')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'لوگ امتیاز',
                'verbose_name_plural': 'لوگ\u200cهای امتیازات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='gamificatio_content_4b865f_idx')],
            },
        ),
    ]
