# Generated by Django 6.0.2 on 2026-05-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='code',
        ),
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(default=None, help_text='کد یکتا برای استفاده در برنامه، مثال: bronze, silver, gold', unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
