# Generated by Django 6.0.2 on 2026-07-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='min_points',
            field=models.IntegerField(default=0, help_text='حداقل امتیاز مورد نیاز برای کسب این سطح', verbose_name='حداقل امتیاز'),
        ),
    ]
