# Generated by Django 6.0.2 on 2026-05-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_badge_code_badge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='reward_amount',
            field=models.PositiveIntegerField(default=0, help_text='مبلغ جایزه نقدی که در هنگام ارتقا به این سطح به کاربر تعلق می\u200cگیرد.', verbose_name='جایزه نقدی (تومان)'),
        ),
    ]
