# Generated by Django 6.0.2 on 2026-05-28 21:13

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_badge_reward_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', help_text='تصویر مربعی ۶۴x۶۴ پیکسل (اختیاری)', keep_meta=False, null=True, quality=90, scale=1, size=[900, 900], upload_to='badges/icons/', verbose_name='آیکون یا تصویر سطح'),
        ),
    ]
