# Generated by Django 6.0.2 on 2026-05-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='badges/icons/', verbose_name='لوگو'),
        ),
    ]
