# Generated by Django 6.0.2 on 2026-05-30 20:46

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_badge_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'لاگ امتیاز', 'verbose_name_plural': 'لاگ های امتیازات'},
        ),
        migrations.RemoveField(
            model_name='badge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
    ]
