# Generated by Django 6.0.2 on 2026-05-30 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_alter_pointlog_options_remove_badge_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='reward_amount',
        ),
    ]
