# Generated by Django 6.0.2 on 2026-05-01 15:46

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('campaign_pending', 'کمپین در انتظار تایید'), ('campaign_approved', 'کمپین تایید شد'), ('campaign_rejected', 'کمپین رد شد'), ('campaign_completed', 'کمپین تمام شد'), ('influencer_accepted', 'اینفلوئنسر سفارش را قبول کرد'), ('influencer_report_approved', 'گزارش اینفلوئنسر تایید شد'), ('ticket_answered', 'تیکت پاسخ داده شد'), ('new_order', 'سفارش جدید'), ('penalty', 'جریمه'), ('report_approved', 'گزارش تایید شد'), ('wallet_deposit', 'واریز به کیف پول'), ('withdrawal_success', 'برداشت موفق'), ('new_content_order', 'سفارش محتوا جدید'), ('revision_requested', 'درخواست ویرایش'), ('final_accepted', 'تایید نهایی سفارش'), ('content_wallet_deposit', 'واریز به حساب تیم'), ('content_withdrawal_success', 'برداشت موفق تیم')], max_length=50, verbose_name='نوع نوتیفیکیشن')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='لینک مرتبط')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه آبجکت مرتبط')),
                ('related_content_type', models.CharField(blank=True, max_length=100, verbose_name='نوع مدل مرتبط')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('read_at', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نوتیفیکیشن',
                'verbose_name_plural': 'نوتیفیکیشن\u200cها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['type'], name='notificatio_type_ea918f_idx')],
            },
        ),
    ]
