# Generated by Django 6.0.2 on 2026-05-24 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_updates', models.BooleanField(default=True, help_text='تایید/رد کمپین، دریافت سفارش جدید، تحویل فایل و...', verbose_name='آپدیت\u200cهای کمپین و سفارشات')),
                ('financial_alerts', models.BooleanField(default=True, help_text='واریز، برداشت، جریمه و صدور فاکتور', verbose_name='تراکنش\u200cهای مالی')),
                ('ticket_replies', models.BooleanField(default=True, verbose_name='پاسخ تیکت\u200cها')),
                ('marketing_messages', models.BooleanField(default=False, verbose_name='اخبار و کدهای تخفیف')),
                ('receive_in_bale', models.BooleanField(default=True, verbose_name='دریافت نوتیفیکیشن در بله')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات نوتیفیکیشن',
                'verbose_name_plural': 'تنظیمات نوتیفیکیشن کاربران',
            },
        ),
    ]
