# Generated by Django 6.0.2 on 2026-05-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('campaign_pending', 'کمپین در انتظار تایید'), ('campaign_approved', 'کمپین تایید شد'), ('campaign_rejected', 'کمپین رد شد'), ('campaign_completed', 'کمپین تمام شد'), ('content_accepted', 'سفارش محتوا قبول شد'), ('content_rejected', 'سفارش محتوا رد شد'), ('content_delivered', 'فایل محتوا تحویل شد'), ('revision_accepted', 'ویرایش قبول شد'), ('revision_rejected', 'ویرایش رد شد'), ('influencer_accepted', 'اینفلوئنسر سفارش را قبول کرد'), ('influencer_report_approved', 'گزارش اینفلوئنسر تایید شد'), ('ticket_answered', 'تیکت پاسخ داده شد'), ('new_order', 'سفارش جدید'), ('penalty', 'جریمه'), ('report_approved', 'گزارش تایید شد'), ('wallet_deposit', 'واریز به کیف پول'), ('withdrawal_success', 'برداشت موفق'), ('new_content_order', 'سفارش محتوا جدید'), ('revision_requested', 'درخواست ویرایش'), ('final_accepted', 'تایید نهایی سفارش'), ('content_wallet_deposit', 'واریز به حساب تیم'), ('content_withdrawal_success', 'برداشت موفق تیم')], max_length=50, verbose_name='نوع نوتیفیکیشن'),
        ),
    ]
