# Generated by Django 6.0.2 on 2026-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='campaign_updates',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='adv_campaign_status',
            field=models.BooleanField(default=True, verbose_name='وضعیت کمپین\u200cها (تایید، رد، اکران، پایان)'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='adv_content_orders',
            field=models.BooleanField(default=True, verbose_name='وضعیت سفارش تولید محتوا (تایید، رد، تحویل فایل)'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='adv_influencer_actions',
            field=models.BooleanField(default=True, verbose_name='واکنش ناشران (پذیرش سفارش تبلیغ)'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='inf_new_orders',
            field=models.BooleanField(default=True, verbose_name='دریافت سفارش تبلیغ جدید'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='inf_report_status',
            field=models.BooleanField(default=True, verbose_name='تایید یا رد گزارش\u200cهای کار'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='team_financial',
            field=models.BooleanField(default=True, verbose_name='تایید نهایی فایل و واریز وجه'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='team_new_orders',
            field=models.BooleanField(default=True, verbose_name='دریافت سفارش تولید محتوای جدید'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='team_revisions',
            field=models.BooleanField(default=True, verbose_name='درخواست ویرایش توسط تبلیغ\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='financial_alerts',
            field=models.BooleanField(default=True, verbose_name='تراکنش\u200cهای مالی (واریز، برداشت، فاکتور)'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='marketing_messages',
            field=models.BooleanField(default=False, verbose_name='اخبار، آپدیت\u200cها و کدهای تخفیف'),
        ),
    ]
